### ISSUE TITLE
Cannot read property 'config' of undefined

### ISSUE THREAD

**Issue by mishranu2** [sbolel/ionic-image-upload#1]
```
ionic.bundle.js:26794 TypeError: Cannot read property 'config' of undefined
    at Object.b (http://localhost:8100/lib/s3-image-uploader/dist/image-uploader.min.js:2:77)
    at new <anonymous> (http://localhost:8100/js/dcontrollers.js:299:23)
    at Object.instantiate (http://localhost:8100/lib/ionic/js/ionic.bundle.js:18010:14)
    at $controller (http://localhost:8100/lib/ionic/js/ionic.bundle.js:23412:28)
    at self.appendViewElement (http://localhost:8100/lib/ionic/js/ionic.bundle.js:59900:24)
    at Object.render (http://localhost:8100/lib/ionic/js/ionic.bundle.js:57893:41)
    at Object.init (http://localhost:8100/lib/ionic/js/ionic.bundle.js:57813:20)
    at self.render (http://localhost:8100/lib/ionic/js/ionic.bundle.js:59759:14)
    at self.register (http://localhost:8100/lib/ionic/js/ionic.bundle.js:59717:10)
    at updateView (http://localhost:8100/lib/ionic/js/ionic.bundle.js:65398:23) <ion-nav-view name="dgroups" class="view-container tab-content" nav-view="active" nav-view-transition="ios">(anonymous function) @ ionic.bundle.js:26794(anonymous function) @ ionic.bundle.js:23507invokeLinkFn @ ionic.bundle.js:22995nodeLinkFn @ ionic.bundle.js:22392compositeLinkFn @ ionic.bundle.js:21703publicLinkFn @ ionic.bundle.js:21583tabSelected @ ionic.bundle.js:67026$digest @ ionic.bundle.js:30239$apply @ ionic.bundle.js:30503done @ ionic.bundle.js:24824completeRequest @ ionic.bundle.js:25022requestLoaded @ ionic.bundle.js:24963
```

**Comment by toddhalfpenny** [comment]
Hey Misha,

I had this just earlier when I was starting out with this;
My issues was to do with not installing 'angular-file-upload' and 'aws-sdk' via npm and copying/including the 2 scripts in my index.html like this;

```
    <script src="lib/js/angular-file-upload.min.js"></script>
    <script src="lib/js/aws-sdk.min.js"></script>
    <script src="lib/js/image-uploader.js"></script>
```

**Comment by sbolel** [comment]
Thank you @toddhalfpenny!
