### ISSUE TITLE
Not working on android 4.4.2

### ISSUE THREAD

**Issue by mishranu2** [sbolel/ionic-image-upload#2]
Working fine on chrome using ionic serve, but not working on device. Returns this error on debugging in app console. 
Please help fix. 

``` sh
TypeError: Object function Object() { [native code] } has no method 'assign'
    at Object.b (file:///android_asset/www/lib/s3-image-uploader/dist/image-uploader.bundle.min.js:38:25746)
    at new <anonymous> (file:///android_asset/www/js/app.js:428:23)
    at Object.invoke (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:17995:19)
    at $controllerInit (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:23397:34)
    at nodeLinkFn (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:22335:34)
    at compositeLinkFn (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:21703:13)
    at compositeLinkFn (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:21706:13)
    at nodeLinkFn (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:22387:24)
    at compositeLinkFn (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:21703:13)
    at nodeLinkFn (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:22387:24) ionic.bundle.js:26794
(anonymous function) ionic.bundle.js:26794
(anonymous function) ionic.bundle.js:23507
Scope.$broadcast ionic.bundle.js:30720
$state.transition.resolved.then.$state.transition ionic.bundle.js:52157
processQueue ionic.bundle.js:29127
(anonymous function) ionic.bundle.js:29143
Scope.$eval ionic.bundle.js:30395
Scope.$digest ionic.bundle.js:30211
Scope.$apply ionic.bundle.js:30503
(anonymous function) ionic.bundle.js:65426
defaultHandlerWrapper ionic.bundle.js:16787
eventHandler ionic.bundle.js:16775
triggerMouseEvent ionic.bundle.js:2953
tapClick ionic.bundle.js:2942
tapTouchEnd ionic.bundle.js:3069
```

**Comment by sbolel** [comment]
@MishRanu Which version of `image-uploader` are you using? [v1.3.0](https://github.com/sbolel/image-uploader/releases/tag/v1.3.0) is the latest.

**Comment by mishranu2** [comment]
yes v1.3.0 but this error doesn't come on versions higher than android 5.1.

**Comment by sbolel** [comment]
Ok, I do not have an android :(

**Comment by sbolel** [comment]
I'm not sure how to test this. @MishRanu -- any updates?
